import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navbar from "@/components/layout/Navbar";
import AnimatedCasinoBackground from "@/components/shared/background";
import Footer from "@/components/layout/Footer";
import BottomHero from "@/components/layout/bottomHero";
import Hero from "@/components/layout/Hero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Fixed animated background for entire website */}
          <AnimatedCasinoBackground
            fixed={true}
            enableParallax={true}
            backgroundColor="bg-[#ffedca] dark:bg-black"
            opacity="opacity-100"
          />

          {/* Main content - positioned above background */}
          <div className="relative min-h-[400vh] ">
            <Navbar />
            {children}
            {/* <Footer /> */}
            {/* Add some spacing to allow for scroll effect */}
            <div className="h-[94vh] invisible pointer-events-none bg-transparent"></div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
